### ISSUE TITLE
output of [INST] <<SYS>><</SYS>> at the end of every answer

### ISSUE THREAD

**Issue by alexmondaini** [shroominic/fastui-chat#5]
I am using your example and ChatOllama instead of openai chatmodel and I get some UI strange characters at the end of every answer.Following is an image :

![Uploading Screenshot 2024-01-11 at 5.24.33 AM.png…]()

**Comment by shroominic** [comment]
I think you can set the stop stop sequence manually to this text this should fix it. 
Not sure where this problem is coming from but I think some models have wrong chat schemas in ollama.
