### ISSUE TITLE
Add document retrieving capabilities 

### ISSUE THREAD

**Issue by alexmondaini** [shroominic/fastui-chat#9]
Rather than an issue , I would be interested on where I could develop some document retrieving (RAG) capabilities into the chatUI. Which files to extend ?

**Comment by shroominic** [comment]
i think for this we need to implement multiple things:
- additional form intput to upload files
- some place to store the files, maybe inside messages
- a rag chat handler loading the files into a retriever and automatically injecting context

**Comment by shroominic** [comment]
feel free to mention your fork here then I can have a look and maybe help out, i want this too haha

**Comment by alexmondaini** [comment]
alright, let me check on that.  Do you know if is easy to add an arrow icon button on the chat form ? is that possible to use the bootstrap class name of fastui alone ?

**Comment by deftio** [comment]
Rather than add UI for uploading the documents, perhaps just make a directory where the documents can be placed as a starter.
then use langchain doc loaders (or equivalent) to RAG the data.

**Comment by shroominic** [comment]
> alright, let me check on that. Do you know if is easy to add an arrow icon button on the chat form ? is that possible to use the bootstrap class name of fastui alone ?

I think a text based emoji button should work not sure about icon buttons

**Comment by shroominic** [comment]
> Rather than add UI for uploading the documents, perhaps just make a directory where the documents can be placed as a starter. then use langchain doc loaders (or equivalent) to RAG the data.

I mean RAG is easy we know how to do this but we are here for building the UI

**Comment by alexmondaini** [comment]
I am trying to implement a simple rag on your `handler.py` but it is failing:

```
from langchain_core.language_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.runnables import RunnablePassthrough
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings


from ...backend.settings import create_local_settings
from ...model.defaults import univeral_model_selector
from ...schema.types import ChatHandler, OptionalChatHistoryFactory, UniversalChatModel
from ...utils.memory import InMemoryChatMessageHistory, create_history_factory
from ...utils.msg_tools import msg_to_str


def load_universal_llm(llm: UniversalChatModel) -> BaseChatModel:
    if isinstance(llm, str):
        settings = create_local_settings({"llm": llm})
        llm = None
    if not llm:
        llm = univeral_model_selector(settings)
    return llm


def create_chat_handler(
    *,
    llm: UniversalChatModel = None,
    history_factory: OptionalChatHistoryFactory = None,
    system_message: str = "",
) -> ChatHandler:
    history_factory = history_factory or create_history_factory(InMemoryChatMessageHistory)
    llm = load_universal_llm(llm)
    vectorstore = FAISS.from_texts(
        ["harrison worked at kensho"], embedding=OpenAIEmbeddings()
    )
    retriever = vectorstore.as_retriever()

    template = """Answer the question based only on the following context:
    {context}

    Question: {message}
    """
    prompt = ChatPromptTemplate.from_template(template)
    chat_handler_chain = (
        {'context': retriever} | 
        ChatPromptTemplate.from_messages(
            [
                # *([("system", system_message)] if system_message else []),  # todo test this
                ("system", "Answer the question based only on the following context: \n {context}."),
                MessagesPlaceholder(variable_name="history"),
                ("human", "{message}"),
            ]
        )
        | llm
    )
    return {
        # todo handle images
        "message": lambda x: msg_to_str(x)
    } | RunnableWithMessageHistory(
        chat_handler_chain,  # type: ignore
        get_session_history=history_factory,
        input_messages_key="message",
        history_messages_key="history",
    )

```

**Comment by alexmondaini** [comment]
I have also tried to use my own custom llm defined in :

https://python.langchain.com/docs/modules/model_io/llms/custom_llm

And this returns a string when calling the llm, however when using with the fastui_chat I bumbed into the following error:

`(await session.invoke(HumanMessage(content=user_msg))).content`

AtttributeError: 'str' object
has no attribute 'content'


I guess the customLLM needs to return a BaseMessage in your case rather than a string ? Is that correct ?
